### PR TITLE
Remove all _5g suffixes from variable/function names

### PR DESCRIPTION
**Pull request by jakobj**
This PR removes all `_5g` suffixes that were used during the initial phase of the project

### CODE REVIEW

**Comment by jakobj** [comment]
thanks! fixed conflicts and removed the `send()` as per your suggestion. please have another look

**Comment by jakobj** [comment]
fixed conflicts

**Comment by jakobj** [comment]
hmm, I can't get `clang-format` to run, since there doesn't seem to be an official repo for 3.6 any more (https://apt.llvm.org/). maybe some one with a working installation could tell me where the errors occur, before I start compiling llvm from sources?

**Comment by heplesser** [comment]
@suku248 It looks like the formatting issues are now fixed. Are you happy with this PR now?

**Pull request merged**
